// <auto-generated />
using System;
using InventoryManagementAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryManagementAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260103035821_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventoryManagementAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 3, 3, 58, 20, 799, DateTimeKind.Utc).AddTicks(7350),
                            Description = "Electronic items and components",
                            Name = "Electronics",
                            UpdatedAt = new DateTime(2026, 1, 3, 3, 58, 20, 799, DateTimeKind.Utc).AddTicks(7350)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 3, 3, 58, 20, 799, DateTimeKind.Utc).AddTicks(7352),
                            Description = "Office stationery and supplies",
                            Name = "Office Supplies",
                            UpdatedAt = new DateTime(2026, 1, 3, 3, 58, 20, 799, DateTimeKind.Utc).AddTicks(7352)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 3, 3, 58, 20, 799, DateTimeKind.Utc).AddTicks(7354),
                            Description = "Office furniture and equipment",
                            Name = "Furniture",
                            UpdatedAt = new DateTime(2026, 1, 3, 3, 58, 20, 799, DateTimeKind.Utc).AddTicks(7354)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 3, 3, 58, 20, 799, DateTimeKind.Utc).AddTicks(7355),
                            Description = "Raw materials for production",
                            Name = "Raw Materials",
                            UpdatedAt = new DateTime(2026, 1, 3, 3, 58, 20, 799, DateTimeKind.Utc).AddTicks(7356)
                        });
                });

            modelBuilder.Entity("InventoryManagementAPI.Models.InventoryMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("InventoryMovements");
                });

            modelBuilder.Entity("InventoryManagementAPI.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("LastRestocked")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("InventoryManagementAPI.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GeneratedBy")
                        .HasColumnType("int");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedBy");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("InventoryManagementAPI.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ItemsSupplied")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "20 Dromo lane",
                            ContactPerson = "John Smith",
                            CreatedAt = new DateTime(2026, 1, 3, 3, 58, 20, 799, DateTimeKind.Utc).AddTicks(7384),
                            Email = "john@techparts.com",
                            ItemsSupplied = 0,
                            Name = "TechParts Inc.",
                            Phone = "+1 (555) 123-4567",
                            Status = "active",
                            UpdatedAt = new DateTime(2026, 1, 3, 3, 58, 20, 799, DateTimeKind.Utc).AddTicks(7385)
                        },
                        new
                        {
                            Id = 2,
                            Address = "45 Paper Street",
                            ContactPerson = "Sarah Johnson",
                            CreatedAt = new DateTime(2026, 1, 3, 3, 58, 20, 799, DateTimeKind.Utc).AddTicks(7387),
                            Email = "sarah@officesupply.com",
                            ItemsSupplied = 0,
                            Name = "Office Supply Co.",
                            Phone = "+1 (555) 987-6543",
                            Status = "active",
                            UpdatedAt = new DateTime(2026, 1, 3, 3, 58, 20, 799, DateTimeKind.Utc).AddTicks(7387)
                        });
                });

            modelBuilder.Entity("InventoryManagementAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "AU",
                            CreatedAt = new DateTime(2026, 1, 3, 3, 58, 20, 799, DateTimeKind.Utc).AddTicks(6202),
                            Email = "admin@inventory.com",
                            IsActive = true,
                            Name = "Admin User",
                            PasswordHash = new byte[] { 223, 107, 66, 93, 237, 59, 56, 248, 145, 115, 243, 65, 154, 232, 206, 2, 102, 109, 69, 97, 223, 180, 123, 178, 237, 39, 185, 1, 110, 95, 223, 30, 131, 12, 150, 217, 174, 44, 107, 14, 19, 125, 102, 248, 254, 34, 135, 109, 1, 110, 226, 237, 250, 142, 119, 99, 93, 217, 93, 133, 44, 199, 174, 184 },
                            PasswordSalt = new byte[] { 100, 131, 124, 158, 143, 98, 185, 98, 220, 240, 242, 67, 116, 233, 136, 114, 170, 185, 115, 164, 107, 101, 38, 39, 171, 107, 184, 246, 33, 235, 137, 48, 108, 54, 91, 246, 29, 187, 250, 39, 169, 125, 146, 209, 41, 28, 103, 236, 247, 77, 157, 33, 0, 17, 137, 195, 250, 95, 189, 81, 136, 108, 67, 249, 60, 196, 170, 203, 50, 163, 153, 94, 196, 40, 20, 128, 234, 125, 82, 116, 225, 235, 74, 67, 9, 7, 190, 236, 60, 244, 204, 156, 6, 107, 157, 173, 192, 0, 143, 221, 245, 153, 243, 17, 221, 221, 225, 67, 177, 148, 108, 182, 137, 116, 211, 137, 154, 97, 14, 78, 18, 217, 192, 246, 242, 207, 91, 197 },
                            Role = "admin"
                        });
                });

            modelBuilder.Entity("InventoryManagementAPI.Models.InventoryMovement", b =>
                {
                    b.HasOne("InventoryManagementAPI.Models.Item", "Item")
                        .WithMany("Movements")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryManagementAPI.Models.User", "User")
                        .WithMany("Movements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InventoryManagementAPI.Models.Item", b =>
                {
                    b.HasOne("InventoryManagementAPI.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryManagementAPI.Models.Supplier", "Supplier")
                        .WithMany("Items")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("InventoryManagementAPI.Models.Report", b =>
                {
                    b.HasOne("InventoryManagementAPI.Models.User", "User")
                        .WithMany("Reports")
                        .HasForeignKey("GeneratedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InventoryManagementAPI.Models.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("InventoryManagementAPI.Models.Item", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("InventoryManagementAPI.Models.Supplier", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("InventoryManagementAPI.Models.User", b =>
                {
                    b.Navigation("Movements");

                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
